### ISSUE TITLE
Add word 'countdown' in repo description and/or repo topics

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/maxlength#4]
I was searching repos in backdrop-contrib for this module but for 'countdown', which I think is one of the main features of this module, I couldn't see it until I thought to search for length. Even then, from the description, I wasn't sure it offered the functionality.

This should probably also feature in the first paragraph of the Readme as that is used in the project browser.

The current description is:

> Maxlength allows you to set maximum length of any field on any form making use of the form API. This includes fields created using the UI.

Perhaps something like:

> Set the maximum length of any field on your Backdrop CMS website and enforce while editing rather than just on save, showing a countdown of remaining characters.

(I've also included 'Backdrop CMS' as per my talk at Backdrop live)

You could also include the keyword and key phrase (i.e. "count down") in topics to further help people find this.

**Comment by laryn** [comment]
Thanks @yorkshire-pudding. I've updated the description and the README.

https://github.com/backdrop-contrib/maxlength/commit/bdf8dbcdad2577f30fd626963759962a12e91d83
